[project]
name = "xml-parser-test"
version = "0.1.0"
description = "Data Engineering Test Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "ruff>=0.14.4",
]
